### ISSUE TITLE
Feature proposal: `yappin` function

### ISSUE THREAD

**Issue by araujo88** [araujo88/brainrot#12]
Currently we have `yapping` builting function that is equivalent to `puts` from C or `printf` but with a newline at the end (`\n`). The `yappin` function would then be sequivalent to `printf`. Let me know if this is cringy or would be bussin up Brainrot lang rizz.

**Comment by filenine** [comment]
Would `yappin` be called in the same ways as `yapping`? That is, would it be called as:
`yappin(2 + 3);`,
or as:
`yappin("%d", 2 + 3);`?

**Comment by araujo88** [comment]
Implemented in https://github.com/araujo88/brainrot/pull/14.
