### ISSUE TITLE
Error with installing compiler [macOS] 

### ISSUE THREAD

**Issue by AyuBloom** [araujo88/brainrot#2]
i followed all the steps for compiling the compiler in order, but got this error:

```sh
> make
bison -d -Wcounterexamples lang.y -o lang.tab.c
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bison: invalid option -- W
Try `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bison --help' for more information.
make: *** [all] Error 1
```

**Comment by XperienceZ** [comment]
@AyuBloom don't use macOS :kekw:

**Comment by araujo88** [comment]
Your bison might be outdated, since the `-Wcounterexamples` flag was added on newest versions. Did you installed it via homebrew? Also, can you please output the version of bison with `bison --version`?

**Comment by araujo88** [comment]
You can simple generate the parser and lexer without the flag, but if you want to contribute to the project you're going to need it.

`bison -d lang.y -o lang.tab.c`

**Comment by AyuBloom** [comment]
> Your bison might be outdated, since the `-Wcounterexamples` flag was added on newest versions. Did you install it via homebrew? Also, can you please output the version of bison with `bison --version`?

My bison version is 2.3. And yes, I did install it via homebrew.

**Comment by AyuBloom** [comment]
Update: It seems like i had a very outdated version of bison. Homebrew didn't link bison first because macOS already preinstalled bison (v2.3).  
I fixed it by following homebrew's instruction:

```sh
echo 'export PATH="/usr/local/opt/bison/bin:$PATH"' >> ~/.zshrc
```

**Comment by AyuBloom** [comment]
I ran into another issue with `flex`:

```sh
> make
bison -d -Wcounterexamples lang.y -o lang.tab.c
flex lang.l
gcc -o brainrot lang.tab.c lex.yy.c ast.c -lfl
ld: library 'fl' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [all] Error 1
```

**Comment by massanf** [comment]
The same issues happened to me. Check if `libfl` is installed at:
```sh
/opt/homebrew/lib/libfl.dylib  # For Apple Silicon
/usr/local/lib/libfl.dylib  # For Intel Macs
```
and if not, you have to find it and symlink to it. Find it using:
```sh
find /opt/homebrew -name "libfl.*"  # For Apple Silicon
find /usr/local -name "libfl.*"  # For Intel Macs
```
and link it with:
```sh
sudo ln -s /path/to/libfl.dylib /opt/homebrew/lib/libfl.dylib  # For Apple Silicon
sudo ln -s /path/to/libfl.dylib /usr/local/lib/libfl.dylib  # For Intel Macs
```

**Comment by AyuBloom** [comment]
I got it all fixed! Thanks. Though I am on an M3 Mac, i had to use the command `For Intel Macs` (maybe because I transferred everything from my old Intel Mac over and homebrew didn't bother to make its own folder, just guessing)
