### ISSUE TITLE
Skibidi `sigma` operator buzz `sigma rule`

### ISSUE THREAD

**Issue by unia909** [araujo88/brainrot#3]
Skibidi operator `sigma` to make coderot more dop dop. With that change `switch_case` example be like:
```
skibidi main {
    schizo rizz choice = 2;
    ohio (choice) {
        sigma rule 1:
            yapping("You chose 1, that's pretty sus!");
            bruh;
        sigma rule 2:
            yapping("You chose 2, gigachad move!");
            bruh;
        sigma rule 3:
            yapping("You chose 3, totally based!");
            bruh;
        based:
            yapping("You chose something unexpected, cringe!");
            bruh;
    }
    bussin 0;
}
```

**Comment by araujo88** [comment]
Your suggestion is an absolute chad move. I'd like to hear more about other fellow chads about this. Please give a thumbs up if you think this keyword modification adds rizz to the language.

**Comment by xxl3rs** [comment]
that right there thats rizz approved i would love to see this for sigmas to griddy with

**Comment by araujo88** [comment]
Implemented in https://github.com/araujo88/brainrot/pull/8. Be bussin fellow sigmas.
