### ISSUE TITLE
cannot do make on mac

### ISSUE THREAD

**Issue by alxlemesh** [araujo88/brainrot#6]
╰─ make
bison -d lang.y -o lang.tab.c
flex lang.l
gcc -o brainrot lang.tab.c lex.yy.c ast.c -lfl
ld: library 'fl' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [all] Error 1

**Comment by araujo88** [comment]
Marked as duplicate: https://github.com/araujo88/brainrot/issues/2
