### ISSUE TITLE
I cant figure out why I'm getting an error.

### ISSUE THREAD

**Issue by VeryElegantBread** [araujo88/brainrot#7]
I can't figure out why I get a syntax error on line 2 of this:

skibidi main {
     goon (1 < 2) { 
          yapping("AAAH UNENDING LOOP");
     }
}

**Comment by Th3F4nd1t** [comment]
This sigma is cooking frfr on these bugs. No cap.

**Comment by araujo88** [comment]
Fixed in https://github.com/araujo88/brainrot/pull/14.
